# Generated by Django 2.0.4 on 2018-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=20)),
                ('courseName', models.CharField(max_length=45)),
                ('courseAttribute', models.CharField(max_length=20)),
                ('courseModule', models.CharField(max_length=45)),
                ('courseType', models.CharField(max_length=45)),
                ('credit', models.FloatField(max_length=12)),
                ('creditHour', models.FloatField(max_length=12)),
                ('introduction', models.CharField(max_length=180)),
                ('pCourseId', models.CharField(max_length=20)),
                ('boundCourseId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=20)),
                ('subjectDes', models.CharField(max_length=512)),
            ],
        ),
    ]
