# Generated by Django 2.0.4 on 2018-04-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializedSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_sub', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=512)),
            ],
        ),
    ]
