# Generated by Django 2.0.3 on 2018-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_coursecategory_coursemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrevious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=128)),
                ('pCourseName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.CharField(max_length=10)),
                ('courseName', models.CharField(max_length=128)),
                ('courseEngName', models.CharField(max_length=128)),
                ('credit', models.FloatField(max_length=12)),
                ('creditHour', models.IntegerField()),
                ('theoryCreditHour', models.IntegerField()),
                ('experimentCreditHour', models.IntegerField()),
                ('practiceCreditHour', models.IntegerField()),
                ('courseModule', models.CharField(max_length=45)),
                ('courseCategory', models.CharField(max_length=45)),
                ('courseAttribution', models.CharField(max_length=45)),
                ('isSchoolCourse', models.CharField(max_length=10)),
                ('isCollegeCourse', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EducationMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('majorName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EducationOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('desc', models.CharField(max_length=180)),
                ('status', models.CharField(max_length=45)),
            ],
        ),
    ]
